#!/usr/bin/env node
require('dotenv').config()
const colors = require('colors')
const clipboardy = require('clipboardy')
const Grial = require('@grial/server')

module.exports = async() => {
  try {
    // run Grial
    const grial = new Grial(process.env)
    await grial.prepare()
    await grial.run()

    // get enviroment variables and format the url
    const { SUBSCRIPTION_PATH = 'subscriptions', HOST = 'localhost', PORT = 3000 } = process.env
    const URL = `http://${HOST}:${PORT}`

    // show log in the console
    console.log(colors.green('Grial server running'))
    console.log(colors.green(`> GraphiQL Endpoint      = ${URL}/ide`))
    console.log(colors.green(`> API Endpoint           = ${URL}/graphql`))
    console.log(colors.green(`> Subscriptions Endpoint = ${URL}/${SUBSCRIPTION_PATH}`))

    // copy the IDE url to the clipboard
    await clipboardy.write(`${URL}/ide`)
    console.log(colors.green('GraphiQL endpoint copied to clipboard'))
  } catch (error) {
    console.error(error)
    process.exit(error)
  }
}
